name: Analyze Code Quality

on: 
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SELISE_GITHUB_PAT:
        required: true

jobs:
  build:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.SELISE_GITHUB_PAT }}

      - name: Set Environment Variables
        uses: ./.github/actions/setvars
        with:
          varFilePath: ./.github/variables/vars.env

      - name: Setup Node version 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.13

      - name: Install dependencies
        run: npm i

      - name: Test and coverage
        run: npm run test -- --coverage

      - name: Change abs paths to rel paths
        working-directory: ./coverage
        run: | 
          sed -i "s|/home/runner/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/||g" lcov.info 

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      - uses: sonarsource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONARQUBE_HOST }}

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@v1.2.0
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONARQUBE_HOST }}
