name: Build (main)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened

env:
  RUN_SONARQUBE: 'false'

jobs:
  initialization:
    permissions:
        contents: read
        id-token: write
    runs-on: ubuntu-latest
    outputs:
      envvalue1: ${{ steps.setvar.outputs.envvar1 }}
    steps:
      - name: set value
        id: setvar
        run: |
          echo envvar1="$RUN_SONARQUBE" >> $GITHUB_OUTPUT

  # sonarqube-job:
  #   if: ${{ success() && needs.initialization.outputs.envvalue1=='true' }}
  #   uses: ./.github/workflows/2_sonar.yml
  #   secrets:
  #     SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_GLOBAL }}
  #   needs: [initialization]

  cd-job:
    if: ${{ github.event_name == 'push' }}
    permissions:
        contents: read
        id-token: write
    uses: ./.github/workflows/3_web.yml
    with:
      CONTAINER_NAME: 'prod-$SERVICE_NAME-webclient'
      NAMESPACE: 'prod-$REPO_NAME'
      SERVICE_NAME: $SERVICE_NAME
      CI_BUILD: 'prod'
    secrets:
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_AKS_BLOCKS_PROD_CREDENTIALS }}
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_BLOCKS_PROD_CONTAINER_REGISTRY }}
      ClUSTER_RESOURCE_GROUP: ${{ secrets.ClUSTER_AKS_BLOCKS_PROD_RESOURCE_GROUP }}
      CLUSTER_NAME: ${{ secrets.AKS_BLOCKS_PROD_CLUSTER }}
      ACR_RESOURCE_GROUP: ${{ secrets.ClUSTER_AKS_BLOCKS_PROD_RESOURCE_GROUP }}
    # needs: [sonarqube-job] 